---
title: "100 Domande"
author: "G. M. Marchetti"
date: "1 giugno 2019"
output:
  pdf_document: default
  html_document:
    highlight: haddock
    theme: cosmo
---

```{r echo = FALSE}
library(knitr)
options(replace.assign=FALSE,width=80, digits = 4)
opts_chunk$set(comment = NA, message = FALSE, fig.width = 2, fig.height = 2)

knit_hooks$set(par=function(before, options, envir){
              if (before && options$fig.show != 'none') par(cex = 0.8, mar=c(4,4,.1,.1),cex.lab=.95,cex.axis=.9,mgp=c(2,.7,0),tcl=-.3)}, crop=hook_pdfcrop)
```

1. Definite una distribuzione di frequenza. Per esempio fare la distribuzione di frequenza dei dati seguenti osservati su 16 famiglie

```
N. Figli 1 3 2 4 3 5 4 2 1 0 4 2 3 0 0  
```

2. Definire i termini seguenti, sui dati precedenti

   * Variabile
   * modalità
   * unità
 

3. Che cos'è la mediana?

   * Tipo di indice
   * Significato
   * Come si calcola
   * Calcolarlo sui dati precedenti 

4. Stessa cosa per la media

5. Spiegare come si calcola la media su una distribuzione di frequenza, cioè 
$$
\bar x = \frac{\sum_{i = 1}^k x_i n_i}{\sum_{i=1}^k n_i} 
$$

6. La media aritmetica come cambia se si aggiunge una costante a tutti i dati?

7. Classificare i tipi di caratteri 

8. Per quali caratteri si può calcolare la media aritmetica?

9. La media aritmetica come cambia se si dividono tutti i dati per 2?

10. Che significa che la media aritmetica gode della proprietà dei minimi quadrati?

11. Per una azienda ho i dati su 100 fatture emesse. La mediana dell'importo delle fatture è 80 Euro. Dire quale è la proporzione di fatture con importo superiore a 80 Euro.  

12. Che cos'è la varianza?

   * Tipo di indice
   * Significato
   * Come si calcola
   * Calcolare la varianza delle temperature 0, 1, -1
   
13.  Che cos'è la deviazione standard?  

   * Tipo di indice
   * Significato
   * Come si calcola

14. Che significa standardizzare una variabile?

15. Data distribuzione di frequenza congiunta per le variabili Salario
e Settore
```
            Settore
Salario   Industria    Servizi 
 <2000       80          40    
>=2000       20          60
```
   * cosa sono le distribuzioni marginali?
   * Qual è l'unità?

16. Data una distribuzione per un carattere discreto qual è la rappresentazione grafica più utile?

17. Che cos'è un istogramma?
    
    * Cosa rappresenta l'altezza dei rettangoli?
    * Cosa rappresenta l'area complessiva sotto l'istogramma?
    * Quando si può usare per variabili qualitative?
    
18. Che cosè uno spazio campionario associato a un eseperimento casuale?
19. Che cosa è un evento elementare?
20. Che cos'è un evento?
21. Definire le operazioni sugli  eventi: intersezione, unione, complemento.
22. Quando due eventi sono disgiunti?
23. Quando due eventi sono esaustivi?
24. Che cos'è l'evento certo? E l'evento impossibile?
25. Se due eventi sono disgiunti qual è la probabilità che si verifichi almeno uno dei due? 
26. Se due eventi sono esaustivi qual è la probabilità che si verifichi almeno uno dei due?
27. La probabilità di un evento che assiomi deve verificare?
28. Come si definisce la probabilità di un evento condizionata al verificarsi di un altro evento?
29. Quando due eventi si dicono indipendenti? Se due eventi sono indipendenti sono anche disgiunti?
30. Spiegare come si calcolano le probabilità $P(A\cap B)$ e $P(A \cup B)$ in generale.
31. Come si può calcolare la probabilità $P(A)$ sapendo la probabilità di 
$P(A\mid B)$, di $P(A\mid \bar B)$ e la probabilità di $P(B)$. 
32. Spiegare la formula di Bayes
33. Che cos'è una variabile casuale discreta? Dare la definizione.
34. Spiegare la differenza tra una variabile discreta e una variabile continua.
35. Definire il valore atteso di una variabile casuale discreta.
36. Quali sono le prorietà del valore atteso?
37. Definire la varianza e la deviazione standard di una variabile discreta.
38. Se $X$ è una variabile che è 1 con probabilità $p$ e $0$ con probabilità $q$ qual è il suo valore atteso e la sua varianza?
39. Quali sono le proprietà delle varianza?
40. Se si hanno due variabili casuali $X$ e $Y$ discrete che cos'è la tabella delle probabilità congiunte?
41. Data la tabella delle probabilità congiunte come si calcola il valore atteso di $X$? Per esempio calcola il valore atteso di $X$ se 
$$
\begin{array}{lcc}
 & Y = 0 & 1 \\
X = 1 & 0.1 & 0.2 \\ 
2 & 0.3 & 0.4 \\
\end{array}
$$
42. Definire la covarianza tra $X$ e $Y$. Come si interpreta?
43. Definire il coefficiente di correlazione tra $X$ e $Y$. Come si interpreta?
44. Se il coefficiente di correlazione è 1 che significa? 
45. Se il coefficiente di correlazione è 0 che significa? Quanto vale la covarianza?
46. Quando due variabili casuali $X$ e $Y$ sono indipendenti?
47. Se il coefficiente di correlazione è 0 le variabili sono indipendenti?
48. Se ho 2 prove che danno come risultato le variabili casuali 
$X$ e $Y$, qual è il valore atteso della somma $S = X+Y$?
49. Qual è la varianza della somma $S$?
50. Qual è la media e quale la varianza della differenza $D = X-Y$?
51. Se le variabili casuali $X$ e $Y$ hanno varianze $16$ e $9$ qual è la deviazione standard della somma $S = X+Y$?
52. Definire che cos'è la variabile casuale Binomiale.
53. Quali sono le modalità della Binomiale?
54. Che cosa è la variabile casuale Bernoulli?
55. Se ho $n$ prove indipendenti che danno come risultati $X_1, \dots, X_n$  che possono o 1 con probabilità $p$ o $0$ con probabilità $q$, qual è la distribuzione di probabilità della somma $S = X_1 + \cdots + X_n$?
56. Qual è la media di $S$? Qual è la varianza di $S$?
57. Qual è la media della proporzione di 1 risultanti, cioè di $S/n$? Quale la sua varianza?
58. Che cos'è la funzione di densità di una variabile continua?
59. In un punto $x$ la funzione di densità $f(x)$ può essere maggiore di 1?
60. In un punto $x$ la funzione di densità $f(x)$ può essere negativa?
61. Se $X$ è continua qual è la probabilità $P(X = x)$?
62. Indicare le proprietà fondamentali della variabile casuale normale. 
63. Se $Z$ è normale standard qual è la varianza di $Z$?
64. Se una variabile casuale ha valore atteso $0$ e deviazione standard $1$ allora è normale standard?
65. La funzione di ripartizione della normale standard quanto vale nel punto $z = 0$?
66. Se $Z$ è normale standard quanto vale $P(Z \le 1.96)$? Quanto vale  $P(Z \le -1.96)$?
67. Un quantile superiore della normale standard si indica con $z_\alpha$. Come è definito?
68. Che cos'è un campione casuale iid di dimensione $n$ da una popolazione definita da una variabile $X$?
69. Che cosa si intende per campionamento casuale con e senza ripetizione? Com4 si distinguono?
70. Che cos'è l'universo dei campioni?
71. Che cos'è una statistica campionaria?
72. Cosa significa che una statistica campionaria viene studiata nell'universo dei campioni?
73. Che cos'è una distribuzione campionaria di una statistica?
74. Qual è la distribuzione campionaria della media aritmetica in campioni estratti da una normale?
75. Qual è la distribuzione campionaria di una proporzione di successi (cioè di 1) in campioni estratti da una popolazione dicotomica? 
76. Qual è la distribuzione campionaria della media aritmetica in campioni estratti da una popolazione non normale? Come si può approssimare? Sotto quali condizioni?
77. Come si può approssimare la distribuzione campionaria di una proporzione di successi? Sotto quali condizioni?
78. Se una popolazione $X$ è normale quali sono le probabilità di osservare un valore compreso nell'intervallo $\mu \pm k \sigma$?
79. Se una popolazione $X$ non è normale e non sis sa che forma abbia, quali sono le probabilità di osservare un valore compreso nell'intervallo $\mu \pm k \sigma$? Si possono calcolare esattamente? 
80. Qual è la differenza tra stima e stimatore?
81. Qual è lo stimatore di $\mu$? 
82. Qual è lo stimatore di $\sigma^2$?
83. Qual è lo stimatore di una proporzione?
84. Quando si dice che uno stimatore è corretto ?
85. Spiegare perché la media aritmetica è sempre uno stimatore corretto  della media della popolazione. 
86. Nella domanda precedente è necessario distinguere tre tipi di medie. Spiegare come.
87. Fare un esempio di uno stimatore non corretto. 
88. Definire l'errore standard di uno stimatore. 
89. Calcolare l'errore standard della media campionaria e della proporzione campionaria. 
90. Che cosa fornisce in più l'errore standard a uno stimatore?
91. Come è fatto un intervallo di confidenza per $\mu$ se si ha un campione da una normale con varianza nota?
92. Come è fatto un intervallo di confidenza per $\mu$ se si ha un campione da una normale con varianza ignota?
93. Che cosa è il livello di confidenza? Quando si dice che si è fatto un intervallo di confidenza al 95% vuol dire che 
   - il 95% degli intervalli nell'universo dei campioni contiene la media della popolazione
   - oppure che la media della popolazione ha probabilità del 95% di trovarsi nell'intervallo che si è ottenuto?
94. Quale statistica ha distribuzione t di Student? La t di Student è simmetrica o asimmetrica? Ha le code più spesse o meno spesse della normale? 
95. Descrivere la procedura dei test delle ipotesi.
96. Che tipi di errore si possono commettere? 
97. Il livello del test che cos'è?
98. Se un test ha un p-value del 5% vuol dire che 
   - nell'universo dei campioni i campioni che portano a rifiutare $H_0$ quando è vera sono il 5%,  
   - oppure che l'ipotesi $H_0$ ha probabilità del 5% di essere vera?
99. Spiegare in che modo il livello di confidenza influisce sull'ampiezza di un intervallo di confidenza.
100. Qual è la statistica test per sottoporre a test l'ipotesi che $p = p_0$ contro una alternativa bilaterale? Qual è la regione di accettazione al livello del 5%? Il test è esatto o approssimato?

